name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.5.1
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  flutter_apns_only:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/flutter-apns.git
      path: flutter_apns_only
      ref: myfragilepak-master

dev_dependencies:
  flutter_test:
    sdk: flutter