name: flutter_apns_example
description: Demonstrates how to use the flutter_apns plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: ">=3.24.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider:

  flutter_local_notifications:
  flutter_apns:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_apns_only:
    path: ../flutter_apns_only
  flutter_apns:
    path: ../flutter_apns