name: flutter_apns_only
description: APNS push notification plugin. Works only on iOS. See flutter_apns for apns & firebase combo
version: 1.5.0-dev.1
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: ">=3.24.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterApnsPlugin